import { RescueData } from './ChatBot'
import { MapPin, AlertTriangle, Heart, FileText, Download } from 'lucide-react'

interface RescueReportProps {
  data: RescueData
}

export default function RescueReport({ data }: RescueReportProps) {
  const urgencyColors = {
    low: 'bg-green-100 text-green-800 border-green-200',
    medium: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    high: 'bg-red-100 text-red-800 border-red-200'
  }

  const downloadReport = () => {
    const reportText = `
STRAY ANIMAL RESCUE REPORT
Generated: ${new Date().toLocaleString()}

Animal Type: ${data.animalType}
Issue/Condition: ${data.issue}
Location: ${data.location}
Urgency Level: ${data.urgency.toUpperCase()}

First Aid Recommendations:
${data.firstAid.map(tip => `• ${tip}`).join('\n')}

---
Generated by Curio - Stray Animal Rescue Assistant
    `.trim()
    
    const blob = new Blob([reportText], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `rescue-report-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="p-4 bg-gray-50">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center space-x-2">
          <FileText className="w-5 h-5 text-primary-500" />
          <h3 className="text-lg font-semibold text-gray-800">Rescue Report Generated</h3>
        </div>
        <button
          onClick={downloadReport}
          className="flex items-center space-x-1 text-sm text-primary-600 hover:text-primary-700"
        >
          <Download className="w-4 h-4" />
          <span>Download</span>
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <div className="bg-white p-3 rounded-lg border">
          <div className="flex items-center space-x-2 mb-2">
            <Heart className="w-4 h-4 text-gray-500" />
            <span className="text-sm font-medium text-gray-700">Animal Type</span>
          </div>
          <p className="text-gray-900 capitalize">{data.animalType}</p>
        </div>

        <div className="bg-white p-3 rounded-lg border">
          <div className="flex items-center space-x-2 mb-2">
            <AlertTriangle className="w-4 h-4 text-gray-500" />
            <span className="text-sm font-medium text-gray-700">Condition</span>
          </div>
          <p className="text-gray-900">{data.issue}</p>
        </div>

        <div className="bg-white p-3 rounded-lg border">
          <div className="flex items-center space-x-2 mb-2">
            <MapPin className="w-4 h-4 text-gray-500" />
            <span className="text-sm font-medium text-gray-700">Location</span>
          </div>
          <p className="text-gray-900">{data.location}</p>
        </div>

        <div className="bg-white p-3 rounded-lg border">
          <div className="flex items-center space-x-2 mb-2">
            <AlertTriangle className="w-4 h-4 text-gray-500" />
            <span className="text-sm font-medium text-gray-700">Urgency Level</span>
          </div>
          <span className={`inline-block px-2 py-1 rounded-full text-xs font-medium border ${urgencyColors[data.urgency]}`}>
            {data.urgency.toUpperCase()}
          </span>
        </div>
      </div>

      {data.firstAid.length > 0 && (
        <div className="bg-white p-4 rounded-lg border">
          <h4 className="text-sm font-medium text-gray-700 mb-2">First Aid Recommendations:</h4>
          <ul className="space-y-1">
            {data.firstAid.map((tip, index) => (
              <li key={index} className="text-sm text-gray-600 flex items-start space-x-2">
                <span className="text-primary-500 mt-1">•</span>
                <span>{tip}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="mt-3 text-xs text-gray-500 text-center">
        Report generated at {new Date().toLocaleString()}
      </div>
    </div>
  )
} 